
#
#	Top-level makefile for the Filesystem Projects
#
#	2003 10 23	R. Krten		released for publication
#


all:
	cd lib ; make
	cd tarfs ; make
	cd ramdisk ; make

clean:
	cd lib ; make clean
	cd tarfs ; make clean
	cd ramdisk ; make clean

install:
	cd lib ; make install
	cd tarfs ; make install
	cd ramdisk ; make install

