
#
#	Top-level makefile for Book Examples
#
#	2003 10 23	R. Krten		created
#


all:
	cd adios ; make
	cd fsys ; make
	cd procfs ; make
	cd web ; make

clean:
	cd adios ; make clean
	cd fsys ; make clean
	cd procfs ; make clean
	cd web ; make clean


install:
	cd adios ; make install
	cd fsys ; make install
	cd procfs ; make install
	cd web ; make install

