
#
#	Top-level makefile for Century Aluminum projects
#
#	2003 06 19	R. Krten		created
#	2003 07 02	R. Krten		added dio144 and iso813 directories
#	2003 07 07	R. Krten		added adioslib
#	2003 10 23	R. Krten		released for publication
#


all:
	cd lib ; make
	cd adios ; make
	cd dio144; make
	cd iso813; make
	cd pcl711 ; make
	cd sim000 ; make
	cd utils ; make

clean:
	cd lib ; make clean
	cd adios ; make clean
	cd dio144; make clean
	cd iso813; make clean
	cd pcl711 ; make clean
	cd sim000 ; make clean
	cd utils ; make clean

install:
	cd lib ; make install
	cd adios ; make install
	cd dio144; make install
	cd iso813; make install
	cd pcl711 ; make install
	cd sim000 ; make install
	cd utils ; make install

